# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b115a8bc696fd9b22a3184271e81036181f58a75c7e0ed400496c532873b9fe93c9898d6d9074e7183142f01bfcb2baaa311948f2ddf883764d1b36d4282fdaf

test:
  secret_key_base: e19efc29effc3f8d5a0c3ea83de2afb41b9b6ffc92d3ae6acdc6610e97838ff977fab63dfcca4173c56e46682ccbc179ab221fcf5f778ee5566b53e4771ec4b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
